export global MusicIcons {
    out property <image> play: @image-url("../icons/lucide-play.svg");
    out property <image> pause: @image-url("../icons/lucide-pause.svg");
    out property <image> skip-back: @image-url("../icons/lucide-skip-back.svg");
    out property <image> skip-forward: @image-url("../icons/lucide-skip-forward.svg");
    out property <image> sequence: @image-url("../icons/lucide-sequence.svg");
    out property <image> shuffle: @image-url("../icons/lucide-shuffle.svg");
    out property <image> repeat-one: @image-url("../icons/lucide-repeat-1.svg");
    out property <image> volume-off: @image-url("../icons/lucide-volume-off.svg");
    out property <image> volume-low: @image-url("../icons/lucide-volume-low.svg");
    out property <image> volume-mid: @image-url("../icons/lucide-volume-mid.svg");
    out property <image> volume-high: @image-url("../icons/lucide-volume-high.svg");
    out property <image> song-list: @image-url("../icons/lucide-song-list.svg");
}
